# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  DTR_IP: 'dtr-ee2-azure.erictankok.dtcntr.net'
  IMAGE_NAME: 'engineering/docker-node-app'
  UCP_USER: 'admin'
  UCP_PASSWORD: 'docker123'

steps:
- script: |
    docker build -f Dockerfile -t $(DTR_IP)/$(IMAGE_NAME) .
    docker tag $(DTR_IP)/$(IMAGE_NAME) $(DTR_IP)/$(IMAGE_NAME):1.$(build.buildId)
  displayName: 'Image Build'

- script: |
    sleep 2
  displayName: 'Image Test'

- script: |
    docker login -u $(UCP_USER) -p $(UCP_PASSWORD) $(DTR_IP)
    docker push $(DTR_IP)/$(IMAGE_NAME):latest
    docker push $(DTR_IP)/$(IMAGE_NAME):1.$(build.buildId)
  displayName: 'Image Push'