version: '3.3'

services:
  app:
    image: $DTR_IP/engineering/docker-node-app:latest
    deploy:
      replicas: 3
      labels:
        - "com.docker.lb.hosts=ee2-nodeapp.erictankok.dtcntr.net"
        - "com.docker.lb.port=4000"
        - "com.docker.lb.network=nodeapp_nodeapp-network"
    environment:
      - "MONGODB_SERVICE_SERVICE_HOST=nodeapp_db"
    networks:
      - nodeapp-network

  db:
    image: clusterhq/mongodb
    deploy:
      replicas: 1
    networks:
      - nodeapp-network
    ports:
     - 27017:27017
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  nodeapp-network:
    driver: overlay
