version: '3.1'

services:
  app:
    image: $DTR_IPADDR/engineering/docker-node-app:latest
    deploy:
      replicas: 3
    environment:
      - "MONGODB_SERVICE_SERVICE_HOST=nodeapp_db"
    ports:
      - 4000:4000
    networks:
      - nodeapp-network

  db:
    image: mongo
    deploy:
      replicas: 1
    networks:
      - nodeapp-network
    ports:
     - 27017:27017
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  nodeapp-network:
    driver: overlay
